version: "master-{build}"

os: Windows Server 2012 R2
platform:
  - x64

environment:
  matrix:
    - ruby_version: 25-x64
    - ruby_version: 26-x64

clone_folder: c:\projects\berkshelf
clone_depth: 1

skip_tags: true
branches:
  only:
    - master
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET CI=true
  - SET BUNDLE_WITHOUT=changelog:docs
  - echo %PATH%
  - bundle install --jobs 3 --retry 3
  - ruby --version
  - gem --version
  - bundler --version

build: off

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rake spec
  - bundle exec cucumber --tags ~@not-windows
