# testing
name: Matrix Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: [2.6, 2.7, 3.0, head ]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - run: git config --global user.email "ci@berkshelf.com"
    - run: git config --global user.name "Berkshelf"
    - run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
           sudo apt-get install graphviz libarchive-dev
         elif [ "$RUNNER_OS" == "Windows" ]; then
           echo "$RUNNER_OS not supported"
           exit 1
         elif [ "$RUNNER_OS" == "macOS" ]; then
           brew install graphviz libarchive
         else
           echo "$RUNNER_OS not supported"
           exit 1
         fi
    - run: bundle install --without changelog --jobs 7 --retry=3
    - run: bundle exec rake
